[package]
name = "sweedule"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2.8"
itertools = "0.10.1"
ordered-float = "2.7.0"
